#data
dataset: mnist
data_path: /data6/user23215430/datasets/mnist
download: False
train: True

#model configuration
model: BadNet
input_channels: 1
output_classes: 10

#training
epoch: 100
batch_size: 256
num_workers: 16
loss_fun: cross_entropy
optimizer: sgd
weight_decay: 0
lr: 0.01
# lr_scheduler: StepLR
# lr_decay_step: 20
# lr_decay_rate: 0.1
# lr_decay_min_lr: 1e-5
