#data
dataset: cifar10_poison
data_path: ../datasets/cifar10
download: False
train: True

#model configuration
model: BadNet
input_channels: 3
output_classes: 10
checkpoint: 

#training
epoch: 100
batch_size: 256
num_workers: 16
loss_fun: cross_entropy
optimizer: sgd
weight_decay: 0
lr: 0.01
# lr_scheduler: StepLR
# lr_decay_step: 20
# lr_decay_rate: 0.1
# lr_decay_min_lr: 1e-5


poisoning_rate: 0.1 #poisoning portion (float, range from 0 to 1, default: 0.1)
trigger_label: 0 #The NO. of trigger label (int, range from 0 to 10, default: 0)
trigger_path: ./datasets/badnet/triggers/trigger_white.png #Trigger Path (default: ./triggers/trigger_white.png)
trigger_size: 5 #Trigger Size (int, default: 5)